//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonTest.Client.HostStatistics.FleetService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FleetService.IFleetService")]
    public interface IFleetService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/LoadFleetState", ReplyAction="http://tempuri.org/IFleetService/LoadFleetStateResponse")]
        AmazonTest.Service.Models.Host.FleetResult LoadFleetState(AmazonTest.Service.Models.Host.FleetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/LoadFleetState", ReplyAction="http://tempuri.org/IFleetService/LoadFleetStateResponse")]
        System.Threading.Tasks.Task<AmazonTest.Service.Models.Host.FleetResult> LoadFleetStateAsync(AmazonTest.Service.Models.Host.FleetRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFleetServiceChannel : AmazonTest.Client.HostStatistics.FleetService.IFleetService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FleetServiceClient : System.ServiceModel.ClientBase<AmazonTest.Client.HostStatistics.FleetService.IFleetService>, AmazonTest.Client.HostStatistics.FleetService.IFleetService {
        
        public FleetServiceClient() {
        }
        
        public FleetServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FleetServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FleetServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FleetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AmazonTest.Service.Models.Host.FleetResult LoadFleetState(AmazonTest.Service.Models.Host.FleetRequest request) {
            return base.Channel.LoadFleetState(request);
        }
        
        public System.Threading.Tasks.Task<AmazonTest.Service.Models.Host.FleetResult> LoadFleetStateAsync(AmazonTest.Service.Models.Host.FleetRequest request) {
            return base.Channel.LoadFleetStateAsync(request);
        }
    }
}
